title: "Kankakee Community College"
url: https://info.kcc.edu
public-url: https://info.kcc.edu
port: 3000
theme: landing-page-gem
timezone: America/Chicago
google-tag_key: GTM-PPXHLQ3
humans_file: true
custom_site_js: false
custom_site_styling: true
# contact_phone: 815-802-8508 ## Uncomment to override default phone no. of 815-802-8500
permalink: pretty
description: > # this means to ignore newlines until "baseurl:"
# Delete this comment and place description on this line
baseurl: "" # the subpath of your site, e.g. /blog
sass:
  sass_dir: assets/scss
  style: expanded
# include:
#   - "_pages"
#   - "_posts"
# include future posts? (true or false)
future: true
# Build settings
markdown: kramdown

include:
  - "_schedule.txt"

exclude:
  - "node_modules"
  - "npm-debug.log"
  - "package.json"
  - "package-lock.json"
  - "README.md"
  - "Gemfile"
  - "Gemfile.lock"
  - "siteicon.png"
  - "webpack.config.js"
  - "buildtools/"
  - "postcss.config.js"

uploads_dir: "uploads/" # specifies the default uploads directory for CloudCannon